// © 2022 and later: Unicode, Inc. and others.
// License & terms of use: http://www.unicode.org/copyright.html
//
// Internal static data tables used by uresbund.cpp
// WARNING: This file is mechanically generated by the CLDR-to-ICU tool
// (see tools/cldr/cldr-to-icu/src/main/java/org/unicode/tool/cldrtoicu/generator/ResourcFallbackCodeGenerator.java).
// DO NOT HAND EDIT!!!

#ifdef INCLUDED_FROM_URESBUND_CPP

//======================================================================
// Default script table
const char scriptCodeChars[] =
    "Aghb\0Ahom\0Arab\0Armi\0Armn\0Avst\0Bamu\0Bass\0Batk\0Beng\0Bopo\0"
    "Brah\0Cakm\0Cans\0Cari\0Cham\0Cher\0Chrs\0Copt\0Cprt\0Cyrl\0Deva\0"
    "Egyp\0Elym\0Ethi\0Geor\0Gong\0Gonm\0Goth\0Gran\0Grek\0Gujr\0Guru\0"
    "Hang\0Hani\0Hans\0Hant\0Hebr\0Hluw\0Hmnp\0Ital\0Java\0Jpan\0Kali\0"
    "Kana\0Kawi\0Khar\0Khmr\0Kits\0Knda\0Kore\0Lana\0Laoo\0Latf\0Latg\0"
    "Lepc\0Lina\0Linb\0Lisu\0Lyci\0Lydi\0Mand\0Mani\0Marc\0Medf\0Merc\0"
    "Mlym\0Modi\0Mong\0Mroo\0Mtei\0Mymr\0Narb\0Newa\0Nkoo\0Nshu\0Ogam\0"
    "Olck\0Orkh\0Orya\0Osge\0Ougr\0Pauc\0Phli\0Phnx\0Plrd\0Prti\0Rjng\0"
    "Rohg\0Runr\0Samr\0Sarb\0Saur\0Sgnw\0Sinh\0Sogd\0Sora\0Soyo\0Sunu\0"
    "Syrc\0Tagb\0Takr\0Tale\0Talu\0Taml\0Tang\0Tavt\0Telu\0Tfng\0Thaa\0"
    "Thai\0Tibt\0Tnsa\0Toto\0Ugar\0Vaii\0Wcho\0Xpeo\0Xsux\0Yiii\0";

const char dsLocaleIDChars[] =
    "aaf\0aao\0aat\0ab\0abh\0abl\0abv\0acm\0acq\0acw\0acx\0adf\0adx\0"
    "ady\0ae\0aeb\0aec\0aee\0aeq\0afb\0agi\0agj\0agx\0ahg\0aho\0ahr\0"
    "aib\0aii\0aij\0ain\0aio\0aiq\0akk\0akv\0alk\0all\0alr\0alt\0alw\0"
    "am\0ams\0amw\0ani\0anp\0anq\0anr\0anu\0aot\0apc\0apd\0aph\0aqc\0"
    "ar\0arc\0arq\0ars\0ary\0arz\0as\0ase\0ask\0asr\0atn\0atv\0auj\0"
    "auz\0av\0avd\0avl\0awa\0awn\0axm\0ayh\0ayl\0ayn\0ayp\0az_IQ\0"
    "az_IR\0az_RU\0azb\0ba\0bal\0bap\0bax\0bbl\0bcq\0bdv\0bdz\0be\0"
    "bee\0bej\0bfb\0bfq\0bft\0bfu\0bfw\0bfy\0bfz\0bg\0bgc\0bgd\0bgn\0"
    "bgp\0bgq\0bgw\0bgx\0bha\0bhb\0bhd\0bhe\0bhh\0bhi\0bhj\0bhm\0bhn\0"
    "bho\0bht\0bhu\0biy\0bjf\0bjj\0bjm\0bkk\0blk\0blt\0bmj\0bn\0bns\0"
    "bo\0bph\0bpx\0bpy\0bqi\0bra\0brb\0brd\0brh\0brk\0bro\0brv\0brw\0"
    "brx\0bsh\0bsk\0bsq\0bst\0btd\0btm\0btv\0bua\0bwe\0bxm\0bxu\0byh\0"
    "byn\0byw\0bzi\0cbn\0ccp\0cde\0cdh\0cdi\0cdj\0cdm\0cdo\0cdz\0ce\0"
    "cgk\0chg\0chm\0chr\0chx\0cih\0cja\0cji\0cjm\0cjy\0ckb\0ckt\0clh\0"
    "clw\0cmg\0cna\0cnp\0cog\0cop\0cpg\0cr\0crh\0crj\0crk\0crl\0crm\0"
    "csh\0csp\0csw\0ctd\0ctg\0ctn\0ctt\0cty\0cu\0cuu\0cv\0czh\0czk\0"
    "daq\0dar\0dcc\0ddo\0def\0deh\0der\0dgl\0dhi\0dhn\0dho\0dhw\0dka\0"
    "dlg\0dmf\0dmk\0dml\0dng\0dnu\0dnv\0doi\0dox\0dre\0drq\0drs\0dry\0"
    "dso\0dty\0dub\0duh\0dus\0dv\0dwk\0dwz\0dz\0dzl\0ecr\0ecy\0egy\0"
    "eky\0el\0emg\0emu\0enf\0enh\0era\0esg\0esh\0ett\0eve\0evn\0fa\0"
    "fay\0faz\0fia\0fmu\0fub\0gan\0gaq\0gas\0gau\0gbj\0gbk\0gbl\0gbm\0"
    "gbz\0gdb\0gdo\0gdx\0gez\0ggg\0gha\0ghe\0gho\0ghr\0ght\0gig\0gin\0"
    "gjk\0gju\0gld\0glh\0glk\0gml\0gmv\0gmy\0goe\0gof\0goj\0gok\0gon\0"
    "got\0gra\0grc\0grt\0gru\0gu\0gvr\0gwc\0gwf\0gwt\0gyo\0gzi\0ha_CM\0"
    "ha_SD\0hac\0hak\0har\0haz\0hbo\0hdy\0he\0hi\0hif\0hii\0hit\0hkh\0"
    "hlb\0hlu\0hmd\0hmj\0hmq\0hnd\0hne\0hnj\0hno\0hoc\0hoh\0hoj\0how\0"
    "hoy\0hpo\0hrt\0hrz\0hsn\0hss\0htx\0hut\0huy\0huz\0hy\0hyw\0ii\0"
    "imy\0inh\0int\0ior\0iru\0isk\0itk\0itl\0iu\0iw\0ja\0jad\0jat\0"
    "jbe\0jbn\0jct\0jda\0jdg\0jdt\0jee\0jge\0ji\0jje\0jkm\0jml\0jna\0"
    "jnd\0jnl\0jns\0jog\0jpa\0jpr\0jrb\0jul\0jun\0juy\0jya\0jye\0ka\0"
    "kaa\0kap\0kaw\0kbd\0kbg\0kbu\0kby\0kca\0kcy\0kdq\0kdt\0ket\0kev\0"
    "kex\0key\0kfa\0kfb\0kfc\0kfd\0kfe\0kfg\0kfh\0kfi\0kfk\0kfm\0kfp\0"
    "kfq\0kfr\0kfs\0kfu\0kfx\0kfy\0kgj\0kgy\0khb\0khf\0khg\0khn\0kho\0"
    "kht\0khv\0khw\0kif\0kim\0kip\0kjg\0kjh\0kjl\0kjo\0kjp\0kjt\0kjz\0"
    "kk\0kk_AF\0kk_CN\0kk_IR\0kk_MN\0kkf\0kkh\0kkt\0kle\0klj\0klr\0"
    "km\0kmj\0kmz\0kn\0knn\0ko\0koi\0kok\0kpt\0kpy\0kqd\0kqy\0kra\0"
    "krc\0krk\0krr\0kru\0krv\0ks\0ksu\0ksw\0ksz\0ktb\0kte\0ktl\0ktp\0"
    "ku_LB\0kuf\0kum\0kv\0kva\0kvq\0kvt\0kvx\0kvy\0kxf\0kxk\0kxm\0"
    "kxp\0ky\0ky_CN\0kyu\0kyv\0kyw\0lab\0lad\0lae\0lah\0lbe\0lbf\0"
    "lbj\0lbm\0lbo\0lbr\0lcp\0lep\0lez\0lhm\0lhs\0lif\0lis\0lkh\0lki\0"
    "lmh\0lmn\0lo\0loy\0lpo\0lrc\0lrk\0lrl\0lsa\0lsd\0lss\0ltc\0luk\0"
    "luu\0luv\0luz\0lwl\0lwm\0lya\0lzh\0mag\0mai\0mby\0mde\0mdf\0mdx\0"
    "mdy\0mfa\0mfi\0mga\0mgp\0mhj\0mid\0mjl\0mjq\0mjr\0mjt\0mju\0mjv\0"
    "mjz\0mk\0mkb\0mke\0mki\0mkm\0ml\0mlf\0mn\0mn_CN\0mnc\0mni\0mnj\0"
    "mns\0mnw\0mpz\0mr\0mra\0mrd\0mrj\0mro\0mrr\0ms_CC\0mtm\0mtr\0"
    "mud\0muk\0mut\0muv\0muz\0mve\0mvf\0mvy\0mvz\0mwr\0mwt\0mww\0my\0"
    "mym\0myv\0myz\0mzn\0nan\0nao\0ncd\0ncq\0ndf\0ne\0neg\0neh\0nei\0"
    "new\0ngt\0nio\0nit\0niv\0nli\0nlm\0nlx\0nmm\0nnp\0nod\0noe\0nog\0"
    "noi\0non\0nos\0npb\0nqo\0nrn\0nsd\0nsf\0nsk\0nst\0nsv\0nty\0ntz\0"
    "nwc\0nwx\0nyl\0nyq\0nyw\0oaa\0oac\0oar\0oav\0obm\0obr\0odk\0oht\0"
    "oj\0ojs\0okm\0oko\0okz\0ola\0ole\0omk\0omp\0omr\0omx\0oon\0or\0"
    "ort\0oru\0orv\0os\0osa\0osc\0osi\0ota\0otb\0otk\0oty\0oui\0pa\0"
    "pa_PK\0pal\0paq\0pbt\0pcb\0pce\0pcf\0pcg\0pch\0pci\0pcj\0peg\0"
    "peo\0pgd\0pgg\0pgl\0pgn\0phd\0phk\0phl\0phn\0pho\0phr\0pht\0phu\0"
    "phv\0phw\0pi\0pka\0pkr\0plk\0pll\0pmh\0pnt\0pra\0prc\0prd\0prt\0"
    "prx\0ps\0psh\0psi\0pst\0psu\0pum\0pwo\0pwr\0pww\0pyx\0qxq\0raa\0"
    "rab\0raf\0rah\0raj\0rav\0rbb\0rdb\0rei\0rhg\0rji\0rjs\0rka\0rki\0"
    "rkt\0rmi\0rmt\0rmz\0rsk\0rtw\0ru\0rue\0rut\0rwr\0ryu\0sa\0sah\0"
    "sam\0sat\0saz\0sbn\0sbu\0sck\0scl\0scp\0sct\0scu\0scx\0sd\0sd_IN\0"
    "sdb\0sdf\0sdg\0sdh\0sdr\0sds\0sel\0sfm\0sga\0sgh\0sgj\0sgr\0sgt\0"
    "sgw\0sgy\0shd\0shi\0shm\0shn\0shu\0shv\0si\0sia\0sip\0siy\0siz\0"
    "sjd\0sjp\0sjt\0skb\0skj\0skr\0smh\0smp\0smu\0smy\0soa\0sog\0soi\0"
    "sou\0spt\0spv\0sqo\0sqq\0sqt\0sr\0srb\0srh\0srx\0srz\0ssh\0sss\0"
    "sts\0stv\0sty\0suz\0sva\0swb\0swi\0swv\0sxu\0syc\0syl\0syn\0syr\0"
    "syw\0ta\0tab\0taj\0tbk\0tcn\0tco\0tcx\0tcy\0tda\0tdb\0tdd\0tdg\0"
    "tdh\0te\0tes\0tg\0tg_PK\0tge\0tgf\0th\0the\0thf\0thi\0thl\0thm\0"
    "thq\0thr\0ths\0ti\0tig\0tij\0tin\0tjl\0tjo\0tkb\0tks\0tkt\0tmr\0"
    "tnv\0tov\0tpu\0tra\0trg\0trm\0trw\0tsd\0tsj\0tt\0tth\0tto\0tts\0"
    "ttz\0tvn\0twm\0txg\0txo\0tyr\0tyv\0ude\0udg\0udi\0udm\0ug\0ug_KZ\0"
    "ug_MN\0uga\0ugh\0ugo\0uk\0uki\0ulc\0unr\0unr_NP\0unx\0ur\0urk\0"
    "ush\0uum\0uz_AF\0uz_CN\0uzs\0vaa\0vaf\0vah\0vai\0vas\0vav\0vay\0"
    "vgr\0vjk\0vmd\0vmh\0wal\0wbk\0wbq\0wbr\0wle\0wlo\0wme\0wne\0wni\0"
    "wsg\0wsv\0wtm\0wuu\0xag\0xal\0xan\0xas\0xco\0xcr\0xdq\0xhe\0xhm\0"
    "xis\0xka\0xkc\0xkf\0xkj\0xkp\0xlc\0xld\0xly\0xmf\0xmn\0xmr\0xna\0"
    "xnr\0xpg\0xpi\0xpm\0xpr\0xrm\0xrn\0xsa\0xsr\0xtq\0xub\0xuj\0xve\0"
    "xvi\0xwo\0xzh\0yai\0ybh\0ybi\0ydg\0yea\0yej\0yeu\0ygp\0yhd\0yi\0"
    "yig\0yih\0yiv\0ykg\0ykh\0yna\0ynk\0yoi\0yoy\0yrk\0ysd\0ysn\0ysp\0"
    "ysr\0ysy\0yud\0yue\0yue_CN\0yug\0yux\0ywq\0ywu\0zau\0zba\0zch\0"
    "zdj\0zeh\0zen\0zgb\0zgh\0zgm\0zgn\0zh\0zh_AU\0zh_BN\0zh_GB\0zh_GF\0"
    "zh_HK\0zh_ID\0zh_MO\0zh_PA\0zh_PF\0zh_PH\0zh_SR\0zh_TH\0zh_TW\0"
    "zh_US\0zh_VN\0zhd\0zhx\0zko\0zkt\0zkz\0zlj\0zln\0zlq\0zqe\0zrg\0"
    "zrp\0zum\0zwa\0zyg\0zyn\0zzj\0";

const int32_t defaultScriptTable[] = {
    0, 330,  // aaf -> Mlym
    4, 10,  // aao -> Arab
    8, 150,  // aat -> Grek
    12, 100,  // ab -> Cyrl
    15, 10,  // abh -> Arab
    19, 435,  // abl -> Rjng
    23, 10,  // abv -> Arab
    27, 10,  // acm -> Arab
    31, 10,  // acq -> Arab
    35, 10,  // acw -> Arab
    39, 10,  // acx -> Arab
    43, 10,  // adf -> Arab
    47, 555,  // adx -> Tibt
    51, 100,  // ady -> Cyrl
    55, 25,  // ae -> Avst
    58, 10,  // aeb -> Arab
    62, 10,  // aec -> Arab
    66, 10,  // aee -> Arab
    70, 10,  // aeq -> Arab
    74, 10,  // afb -> Arab
    78, 105,  // agi -> Deva
    82, 120,  // agj -> Ethi
    86, 100,  // agx -> Cyrl
    90, 120,  // ahg -> Ethi
    94, 5,  // aho -> Ahom
    98, 105,  // ahr -> Deva
    102, 10,  // aib -> Arab
    106, 495,  // aii -> Syrc
    110, 185,  // aij -> Hebr
    114, 220,  // ain -> Kana
    118, 355,  // aio -> Mymr
    122, 10,  // aiq -> Arab
    126, 590,  // akk -> Xsux
    130, 100,  // akv -> Cyrl
    134, 260,  // alk -> Laoo
    138, 330,  // all -> Mlym
    142, 100,  // alr -> Cyrl
    146, 100,  // alt -> Cyrl
    150, 120,  // alw -> Ethi
    154, 120,  // am -> Ethi
    157, 210,  // ams -> Jpan
    161, 495,  // amw -> Syrc
    165, 100,  // ani -> Cyrl
    169, 105,  // anp -> Deva
    173, 105,  // anq -> Deva
    177, 105,  // anr -> Deva
    181, 120,  // anu -> Ethi
    185, 45,  // aot -> Beng
    189, 10,  // apc -> Arab
    193, 10,  // apd -> Arab
    197, 105,  // aph -> Deva
    201, 100,  // aqc -> Cyrl
    205, 10,  // ar -> Arab
    208, 15,  // arc -> Armi
    212, 10,  // arq -> Arab
    216, 10,  // ars -> Arab
    220, 10,  // ary -> Arab
    224, 10,  // arz -> Arab
    228, 45,  // as -> Beng
    231, 465,  // ase -> Sgnw
    235, 10,  // ask -> Arab
    239, 105,  // asr -> Deva
    243, 10,  // atn -> Arab
    247, 100,  // atv -> Cyrl
    251, 10,  // auj -> Arab
    255, 10,  // auz -> Arab
    259, 100,  // av -> Cyrl
    262, 10,  // avd -> Arab
    266, 10,  // avl -> Arab
    270, 105,  // awa -> Deva
    274, 120,  // awn -> Ethi
    278, 20,  // axm -> Armn
    282, 10,  // ayh -> Arab
    286, 10,  // ayl -> Arab
    290, 10,  // ayn -> Arab
    294, 10,  // ayp -> Arab
    298, 10,  // az_IQ -> Arab
    304, 10,  // az_IR -> Arab
    310, 100,  // az_RU -> Cyrl
    316, 10,  // azb -> Arab
    320, 100,  // ba -> Cyrl
    323, 10,  // bal -> Arab
    327, 105,  // bap -> Deva
    331, 30,  // bax -> Bamu
    335, 125,  // bbl -> Geor
    339, 120,  // bcq -> Ethi
    343, 395,  // bdv -> Orya
    347, 10,  // bdz -> Arab
    351, 100,  // be -> Cyrl
    354, 105,  // bee -> Deva
    358, 10,  // bej -> Arab
    362, 105,  // bfb -> Deva
    366, 520,  // bfq -> Taml
    370, 10,  // bft -> Arab
    374, 555,  // bfu -> Tibt
    378, 395,  // bfw -> Orya
    382, 105,  // bfy -> Deva
    386, 105,  // bfz -> Deva
    390, 100,  // bg -> Cyrl
    393, 105,  // bgc -> Deva
    397, 105,  // bgd -> Deva
    401, 10,  // bgn -> Arab
    405, 10,  // bgp -> Arab
    409, 105,  // bgq -> Deva
    413, 105,  // bgw -> Deva
    417, 150,  // bgx -> Grek
    421, 105,  // bha -> Deva
    425, 105,  // bhb -> Deva
    429, 105,  // bhd -> Deva
    433, 10,  // bhe -> Arab
    437, 100,  // bhh -> Cyrl
    441, 105,  // bhi -> Deva
    445, 105,  // bhj -> Deva
    449, 10,  // bhm -> Arab
    453, 495,  // bhn -> Syrc
    457, 105,  // bho -> Deva
    461, 105,  // bht -> Deva
    465, 105,  // bhu -> Deva
    469, 105,  // biy -> Deva
    473, 495,  // bjf -> Syrc
    477, 105,  // bjj -> Deva
    481, 10,  // bjm -> Arab
    485, 555,  // bkk -> Tibt
    489, 355,  // blk -> Mymr
    493, 530,  // blt -> Tavt
    497, 105,  // bmj -> Deva
    501, 45,  // bn -> Beng
    504, 105,  // bns -> Deva
    508, 555,  // bo -> Tibt
    511, 100,  // bph -> Cyrl
    515, 105,  // bpx -> Deva
    519, 45,  // bpy -> Beng
    523, 10,  // bqi -> Arab
    527, 105,  // bra -> Deva
    531, 235,  // brb -> Khmr
    535, 105,  // brd -> Deva
    539, 10,  // brh -> Arab
    543, 10,  // brk -> Arab
    547, 555,  // bro -> Tibt
    551, 260,  // brv -> Laoo
    555, 245,  // brw -> Knda
    559, 105,  // brx -> Deva
    563, 10,  // bsh -> Arab
    567, 10,  // bsk -> Arab
    571, 35,  // bsq -> Bass
    575, 120,  // bst -> Ethi
    579, 40,  // btd -> Batk
    583, 40,  // btm -> Batk
    587, 105,  // btv -> Deva
    591, 100,  // bua -> Cyrl
    595, 355,  // bwe -> Mymr
    599, 100,  // bxm -> Cyrl
    603, 340,  // bxu -> Mong
    607, 105,  // byh -> Deva
    611, 120,  // byn -> Ethi
    615, 105,  // byw -> Deva
    619, 550,  // bzi -> Thai
    623, 550,  // cbn -> Thai
    627, 60,  // ccp -> Cakm
    631, 535,  // cde -> Telu
    635, 105,  // cdh -> Deva
    639, 155,  // cdi -> Gujr
    643, 105,  // cdj -> Deva
    647, 105,  // cdm -> Deva
    651, 175,  // cdo -> Hans
    655, 45,  // cdz -> Beng
    659, 100,  // ce -> Cyrl
    662, 555,  // cgk -> Tibt
    666, 10,  // chg -> Arab
    670, 100,  // chm -> Cyrl
    674, 80,  // chr -> Cher
    678, 105,  // chx -> Deva
    682, 105,  // cih -> Deva
    686, 10,  // cja -> Arab
    690, 100,  // cji -> Cyrl
    694, 75,  // cjm -> Cham
    698, 175,  // cjy -> Hans
    702, 10,  // ckb -> Arab
    706, 100,  // ckt -> Cyrl
    710, 10,  // clh -> Arab
    714, 100,  // clw -> Cyrl
    718, 485,  // cmg -> Soyo
    722, 555,  // cna -> Tibt
    726, 175,  // cnp -> Hans
    730, 550,  // cog -> Thai
    734, 90,  // cop -> Copt
    738, 150,  // cpg -> Grek
    742, 65,  // cr -> Cans
    745, 100,  // crh -> Cyrl
    749, 65,  // crj -> Cans
    753, 65,  // crk -> Cans
    757, 65,  // crl -> Cans
    761, 65,  // crm -> Cans
    765, 355,  // csh -> Mymr
    769, 175,  // csp -> Hans
    773, 65,  // csw -> Cans
    777, 410,  // ctd -> Pauc
    781, 45,  // ctg -> Beng
    785, 105,  // ctn -> Deva
    789, 520,  // ctt -> Taml
    793, 520,  // cty -> Taml
    797, 100,  // cu -> Cyrl
    800, 255,  // cuu -> Lana
    804, 100,  // cv -> Cyrl
    807, 175,  // czh -> Hans
    811, 185,  // czk -> Hebr
    815, 105,  // daq -> Deva
    819, 100,  // dar -> Cyrl
    823, 10,  // dcc -> Arab
    827, 100,  // ddo -> Cyrl
    831, 10,  // def -> Arab
    835, 10,  // deh -> Arab
    839, 45,  // der -> Beng
    843, 10,  // dgl -> Arab
    847, 105,  // dhi -> Deva
    851, 155,  // dhn -> Gujr
    855, 105,  // dho -> Deva
    859, 105,  // dhw -> Deva
    863, 555,  // dka -> Tibt
    867, 100,  // dlg -> Cyrl
    871, 320,  // dmf -> Medf
    875, 10,  // dmk -> Arab
    879, 10,  // dml -> Arab
    883, 100,  // dng -> Cyrl
    887, 355,  // dnu -> Mymr
    891, 355,  // dnv -> Mymr
    895, 105,  // doi -> Deva
    899, 120,  // dox -> Ethi
    903, 555,  // dre -> Tibt
    907, 105,  // drq -> Deva
    911, 120,  // drs -> Ethi
    915, 105,  // dry -> Deva
    919, 395,  // dso -> Orya
    923, 105,  // dty -> Deva
    927, 155,  // dub -> Gujr
    931, 105,  // duh -> Deva
    935, 105,  // dus -> Deva
    939, 545,  // dv -> Thaa
    942, 395,  // dwk -> Orya
    946, 105,  // dwz -> Deva
    950, 555,  // dz -> Tibt
    953, 555,  // dzl -> Tibt
    957, 150,  // ecr -> Grek
    961, 95,  // ecy -> Cprt
    965, 110,  // egy -> Egyp
    969, 215,  // eky -> Kali
    973, 150,  // el -> Grek
    976, 105,  // emg -> Deva
    980, 105,  // emu -> Deva
    984, 100,  // enf -> Cyrl
    988, 100,  // enh -> Cyrl
    992, 520,  // era -> Taml
    996, 135,  // esg -> Gonm
    1000, 10,  // esh -> Arab
    1004, 200,  // ett -> Ital
    1008, 100,  // eve -> Cyrl
    1012, 100,  // evn -> Cyrl
    1016, 10,  // fa -> Arab
    1019, 10,  // fay -> Arab
    1023, 10,  // faz -> Arab
    1027, 10,  // fia -> Arab
    1031, 105,  // fmu -> Deva
    1035, 10,  // fub -> Arab
    1039, 175,  // gan -> Hans
    1043, 395,  // gaq -> Orya
    1047, 155,  // gas -> Gujr
    1051, 535,  // gau -> Telu
    1055, 395,  // gbj -> Orya
    1059, 105,  // gbk -> Deva
    1063, 155,  // gbl -> Gujr
    1067, 105,  // gbm -> Deva
    1071, 10,  // gbz -> Arab
    1075, 395,  // gdb -> Orya
    1079, 100,  // gdo -> Cyrl
    1083, 105,  // gdx -> Deva
    1087, 120,  // gez -> Ethi
    1091, 10,  // ggg -> Arab
    1095, 10,  // gha -> Arab
    1099, 105,  // ghe -> Deva
    1103, 540,  // gho -> Tfng
    1107, 10,  // ghr -> Arab
    1111, 555,  // ght -> Tibt
    1115, 10,  // gig -> Arab
    1119, 100,  // gin -> Cyrl
    1123, 10,  // gjk -> Arab
    1127, 10,  // gju -> Arab
    1131, 100,  // gld -> Cyrl
    1135, 10,  // glh -> Arab
    1139, 10,  // glk -> Arab
    1143, 265,  // gml -> Latf
    1147, 120,  // gmv -> Ethi
    1151, 285,  // gmy -> Linb
    1155, 555,  // goe -> Tibt
    1159, 120,  // gof -> Ethi
    1163, 105,  // goj -> Deva
    1167, 105,  // gok -> Deva
    1171, 105,  // gon -> Deva
    1175, 140,  // got -> Goth
    1179, 105,  // gra -> Deva
    1183, 95,  // grc -> Cprt
    1187, 45,  // grt -> Beng
    1191, 120,  // gru -> Ethi
    1195, 155,  // gu -> Gujr
    1198, 105,  // gvr -> Deva
    1202, 10,  // gwc -> Arab
    1206, 10,  // gwf -> Arab
    1210, 10,  // gwt -> Arab
    1214, 105,  // gyo -> Deva
    1218, 10,  // gzi -> Arab
    1222, 10,  // ha_CM -> Arab
    1228, 10,  // ha_SD -> Arab
    1234, 10,  // hac -> Arab
    1238, 175,  // hak -> Hans
    1242, 120,  // har -> Ethi
    1246, 10,  // haz -> Arab
    1250, 185,  // hbo -> Hebr
    1254, 120,  // hdy -> Ethi
    1258, 185,  // he -> Hebr
    1261, 105,  // hi -> Deva
    1264, 105,  // hif -> Deva
    1268, 505,  // hii -> Takr
    1272, 590,  // hit -> Xsux
    1276, 10,  // hkh -> Arab
    1280, 105,  // hlb -> Deva
    1284, 190,  // hlu -> Hluw
    1288, 425,  // hmd -> Plrd
    1292, 50,  // hmj -> Bopo
    1296, 50,  // hmq -> Bopo
    1300, 10,  // hnd -> Arab
    1304, 105,  // hne -> Deva
    1308, 195,  // hnj -> Hmnp
    1312, 10,  // hno -> Arab
    1316, 105,  // hoc -> Deva
    1320, 10,  // hoh -> Arab
    1324, 105,  // hoj -> Deva
    1328, 170,  // how -> Hani
    1332, 105,  // hoy -> Deva
    1336, 355,  // hpo -> Mymr
    1340, 495,  // hrt -> Syrc
    1344, 10,  // hrz -> Arab
    1348, 175,  // hsn -> Hans
    1352, 10,  // hss -> Arab
    1356, 590,  // htx -> Xsux
    1360, 105,  // hut -> Deva
    1364, 185,  // huy -> Hebr
    1368, 100,  // huz -> Cyrl
    1372, 20,  // hy -> Armn
    1375, 20,  // hyw -> Armn
    1379, 595,  // ii -> Yiii
    1382, 295,  // imy -> Lyci
    1386, 100,  // inh -> Cyrl
    1390, 355,  // int -> Mymr
    1394, 120,  // ior -> Ethi
    1398, 520,  // iru -> Taml
    1402, 10,  // isk -> Arab
    1406, 185,  // itk -> Hebr
    1410, 100,  // itl -> Cyrl
    1414, 65,  // iu -> Cans
    1417, 185,  // iw -> Hebr
    1420, 210,  // ja -> Jpan
    1423, 10,  // jad -> Arab
    1427, 10,  // jat -> Arab
    1431, 185,  // jbe -> Hebr
    1435, 10,  // jbn -> Arab
    1439, 100,  // jct -> Cyrl
    1443, 555,  // jda -> Tibt
    1447, 10,  // jdg -> Arab
    1451, 100,  // jdt -> Cyrl
    1455, 105,  // jee -> Deva
    1459, 125,  // jge -> Geor
    1463, 185,  // ji -> Hebr
    1466, 165,  // jje -> Hang
    1470, 355,  // jkm -> Mymr
    1474, 105,  // jml -> Deva
    1478, 505,  // jna -> Takr
    1482, 10,  // jnd -> Arab
    1486, 105,  // jnl -> Deva
    1490, 105,  // jns -> Deva
    1494, 10,  // jog -> Arab
    1498, 185,  // jpa -> Hebr
    1502, 185,  // jpr -> Hebr
    1506, 185,  // jrb -> Hebr
    1510, 105,  // jul -> Deva
    1514, 395,  // jun -> Orya
    1518, 395,  // juy -> Orya
    1522, 555,  // jya -> Tibt
    1526, 185,  // jye -> Hebr
    1530, 125,  // ka -> Geor
    1533, 100,  // kaa -> Cyrl
    1537, 100,  // kap -> Cyrl
    1541, 225,  // kaw -> Kawi
    1545, 100,  // kbd -> Cyrl
    1549, 555,  // kbg -> Tibt
    1553, 10,  // kbu -> Arab
    1557, 10,  // kby -> Arab
    1561, 100,  // kca -> Cyrl
    1565, 10,  // kcy -> Arab
    1569, 45,  // kdq -> Beng
    1573, 550,  // kdt -> Thai
    1577, 100,  // ket -> Cyrl
    1581, 330,  // kev -> Mlym
    1585, 105,  // kex -> Deva
    1589, 535,  // key -> Telu
    1593, 245,  // kfa -> Knda
    1597, 105,  // kfb -> Deva
    1601, 535,  // kfc -> Telu
    1605, 245,  // kfd -> Knda
    1609, 520,  // kfe -> Taml
    1613, 245,  // kfg -> Knda
    1617, 330,  // kfh -> Mlym
    1621, 520,  // kfi -> Taml
    1625, 105,  // kfk -> Deva
    1629, 10,  // kfm -> Arab
    1633, 105,  // kfp -> Deva
    1637, 105,  // kfq -> Deva
    1641, 105,  // kfr -> Deva
    1645, 105,  // kfs -> Deva
    1649, 105,  // kfu -> Deva
    1653, 105,  // kfx -> Deva
    1657, 105,  // kfy -> Deva
    1661, 105,  // kgj -> Deva
    1665, 105,  // kgy -> Deva
    1669, 515,  // khb -> Talu
    1673, 550,  // khf -> Thai
    1677, 555,  // khg -> Tibt
    1681, 105,  // khn -> Deva
    1685, 55,  // kho -> Brah
    1689, 355,  // kht -> Mymr
    1693, 100,  // khv -> Cyrl
    1697, 10,  // khw -> Arab
    1701, 105,  // kif -> Deva
    1705, 100,  // kim -> Cyrl
    1709, 105,  // kip -> Deva
    1713, 260,  // kjg -> Laoo
    1717, 100,  // kjh -> Cyrl
    1721, 105,  // kjl -> Deva
    1725, 105,  // kjo -> Deva
    1729, 355,  // kjp -> Mymr
    1733, 550,  // kjt -> Thai
    1737, 555,  // kjz -> Tibt
    1741, 100,  // kk -> Cyrl
    1744, 10,  // kk_AF -> Arab
    1750, 10,  // kk_CN -> Arab
    1756, 10,  // kk_IR -> Arab
    1762, 10,  // kk_MN -> Arab
    1768, 555,  // kkf -> Tibt
    1772, 255,  // kkh -> Lana
    1776, 105,  // kkt -> Deva
    1780, 105,  // kle -> Deva
    1784, 10,  // klj -> Arab
    1788, 105,  // klr -> Deva
    1792, 235,  // km -> Khmr
    1795, 105,  // kmj -> Deva
    1799, 10,  // kmz -> Arab
    1803, 245,  // kn -> Knda
    1806, 105,  // knn -> Deva
    1810, 250,  // ko -> Kore
    1813, 100,  // koi -> Cyrl
    1817, 105,  // kok -> Deva
    1821, 100,  // kpt -> Cyrl
    1825, 100,  // kpy -> Cyrl
    1829, 495,  // kqd -> Syrc
    1833, 120,  // kqy -> Ethi
    1837, 105,  // kra -> Deva
    1841, 100,  // krc -> Cyrl
    1845, 100,  // krk -> Cyrl
    1849, 235,  // krr -> Khmr
    1853, 105,  // kru -> Deva
    1857, 235,  // krv -> Khmr
    1861, 10,  // ks -> Arab
    1864, 355,  // ksu -> Mymr
    1868, 355,  // ksw -> Mymr
    1872, 105,  // ksz -> Deva
    1876, 120,  // ktb -> Ethi
    1880, 105,  // kte -> Deva
    1884, 10,  // ktl -> Arab
    1888, 425,  // ktp -> Plrd
    1892, 10,  // ku_LB -> Arab
    1898, 260,  // kuf -> Laoo
    1902, 100,  // kum -> Cyrl
    1906, 100,  // kv -> Cyrl
    1909, 100,  // kva -> Cyrl
    1913, 355,  // kvq -> Mymr
    1917, 355,  // kvt -> Mymr
    1921, 10,  // kvx -> Arab
    1925, 215,  // kvy -> Kali
    1929, 355,  // kxf -> Mymr
    1933, 355,  // kxk -> Mymr
    1937, 550,  // kxm -> Thai
    1941, 10,  // kxp -> Arab
    1945, 100,  // ky -> Cyrl
    1948, 10,  // ky_CN -> Arab
    1954, 215,  // kyu -> Kali
    1958, 105,  // kyv -> Deva
    1962, 105,  // kyw -> Deva
    1966, 280,  // lab -> Lina
    1970, 185,  // lad -> Hebr
    1974, 105,  // lae -> Deva
    1978, 10,  // lah -> Arab
    1982, 100,  // lbe -> Cyrl
    1986, 105,  // lbf -> Deva
    1990, 555,  // lbj -> Tibt
    1994, 105,  // lbm -> Deva
    1998, 260,  // lbo -> Laoo
    2002, 105,  // lbr -> Deva
    2006, 550,  // lcp -> Thai
    2010, 275,  // lep -> Lepc
    2014, 100,  // lez -> Cyrl
    2018, 105,  // lhm -> Deva
    2022, 495,  // lhs -> Syrc
    2026, 105,  // lif -> Deva
    2030, 290,  // lis -> Lisu
    2034, 555,  // lkh -> Tibt
    2038, 10,  // lki -> Arab
    2042, 105,  // lmh -> Deva
    2046, 535,  // lmn -> Telu
    2050, 260,  // lo -> Laoo
    2053, 105,  // loy -> Deva
    2057, 425,  // lpo -> Plrd
    2061, 10,  // lrc -> Arab
    2065, 10,  // lrk -> Arab
    2069, 10,  // lrl -> Arab
    2073, 10,  // lsa -> Arab
    2077, 185,  // lsd -> Hebr
    2081, 10,  // lss -> Arab
    2085, 180,  // ltc -> Hant
    2089, 555,  // luk -> Tibt
    2093, 105,  // luu -> Deva
    2097, 10,  // luv -> Arab
    2101, 10,  // luz -> Arab
    2105, 550,  // lwl -> Thai
    2109, 550,  // lwm -> Thai
    2113, 555,  // lya -> Tibt
    2117, 175,  // lzh -> Hans
    2121, 105,  // mag -> Deva
    2125, 105,  // mai -> Deva
    2129, 10,  // mby -> Arab
    2133, 10,  // mde -> Arab
    2137, 100,  // mdf -> Cyrl
    2141, 120,  // mdx -> Ethi
    2145, 120,  // mdy -> Ethi
    2149, 10,  // mfa -> Arab
    2153, 10,  // mfi -> Arab
    2157, 270,  // mga -> Latg
    2161, 105,  // mgp -> Deva
    2165, 10,  // mhj -> Arab
    2169, 305,  // mid -> Mand
    2173, 105,  // mjl -> Deva
    2177, 330,  // mjq -> Mlym
    2181, 330,  // mjr -> Mlym
    2185, 105,  // mjt -> Deva
    2189, 535,  // mju -> Telu
    2193, 330,  // mjv -> Mlym
    2197, 105,  // mjz -> Deva
    2201, 100,  // mk -> Cyrl
    2204, 105,  // mkb -> Deva
    2208, 105,  // mke -> Deva
    2212, 10,  // mki -> Arab
    2216, 550,  // mkm -> Thai
    2220, 330,  // ml -> Mlym
    2223, 550,  // mlf -> Thai
    2227, 100,  // mn -> Cyrl
    2230, 340,  // mn_CN -> Mong
    2236, 340,  // mnc -> Mong
    2240, 45,  // mni -> Beng
    2244, 10,  // mnj -> Arab
    2248, 100,  // mns -> Cyrl
    2252, 355,  // mnw -> Mymr
    2256, 550,  // mpz -> Thai
    2260, 105,  // mr -> Deva
    2263, 550,  // mra -> Thai
    2267, 105,  // mrd -> Deva
    2271, 100,  // mrj -> Cyrl
    2275, 345,  // mro -> Mroo
    2279, 105,  // mrr -> Deva
    2283, 10,  // ms_CC -> Arab
    2289, 100,  // mtm -> Cyrl
    2293, 105,  // mtr -> Deva
    2297, 100,  // mud -> Cyrl
    2301, 555,  // muk -> Tibt
    2305, 105,  // mut -> Deva
    2309, 520,  // muv -> Taml
    2313, 120,  // muz -> Ethi
    2317, 10,  // mve -> Arab
    2321, 340,  // mvf -> Mong
    2325, 10,  // mvy -> Arab
    2329, 120,  // mvz -> Ethi
    2333, 105,  // mwr -> Deva
    2337, 355,  // mwt -> Mymr
    2341, 195,  // mww -> Hmnp
    2345, 355,  // my -> Mymr
    2348, 120,  // mym -> Ethi
    2352, 100,  // myv -> Cyrl
    2356, 305,  // myz -> Mand
    2360, 10,  // mzn -> Arab
    2364, 175,  // nan -> Hans
    2368, 105,  // nao -> Deva
    2372, 105,  // ncd -> Deva
    2376, 260,  // ncq -> Laoo
    2380, 100,  // ndf -> Cyrl
    2384, 105,  // ne -> Deva
    2387, 100,  // neg -> Cyrl
    2391, 555,  // neh -> Tibt
    2395, 590,  // nei -> Xsux
    2399, 105,  // new -> Deva
    2403, 260,  // ngt -> Laoo
    2407, 100,  // nio -> Cyrl
    2411, 535,  // nit -> Telu
    2415, 100,  // niv -> Cyrl
    2419, 10,  // nli -> Arab
    2423, 10,  // nlm -> Arab
    2427, 105,  // nlx -> Deva
    2431, 105,  // nmm -> Deva
    2435, 580,  // nnp -> Wcho
    2439, 255,  // nod -> Lana
    2443, 105,  // noe -> Deva
    2447, 100,  // nog -> Cyrl
    2451, 105,  // noi -> Deva
    2455, 445,  // non -> Runr
    2459, 595,  // nos -> Yiii
    2463, 555,  // npb -> Tibt
    2467, 370,  // nqo -> Nkoo
    2471, 445,  // nrn -> Runr
    2475, 595,  // nsd -> Yiii
    2479, 595,  // nsf -> Yiii
    2483, 65,  // nsk -> Cans
    2487, 560,  // nst -> Tnsa
    2491, 595,  // nsv -> Yiii
    2495, 595,  // nty -> Yiii
    2499, 10,  // ntz -> Arab
    2503, 365,  // nwc -> Newa
    2507, 105,  // nwx -> Deva
    2511, 550,  // nyl -> Thai
    2515, 10,  // nyq -> Arab
    2519, 550,  // nyw -> Thai
    2523, 100,  // oaa -> Cyrl
    2527, 100,  // oac -> Cyrl
    2531, 495,  // oar -> Syrc
    2535, 125,  // oav -> Geor
    2539, 420,  // obm -> Phnx
    2543, 355,  // obr -> Mymr
    2547, 10,  // odk -> Arab
    2551, 590,  // oht -> Xsux
    2555, 65,  // oj -> Cans
    2558, 65,  // ojs -> Cans
    2562, 165,  // okm -> Hang
    2566, 170,  // oko -> Hani
    2570, 235,  // okz -> Khmr
    2574, 105,  // ola -> Deva
    2578, 555,  // ole -> Tibt
    2582, 100,  // omk -> Cyrl
    2586, 350,  // omp -> Mtei
    2590, 335,  // omr -> Modi
    2594, 355,  // omx -> Mymr
    2598, 105,  // oon -> Deva
    2602, 395,  // or -> Orya
    2605, 535,  // ort -> Telu
    2609, 10,  // oru -> Arab
    2613, 100,  // orv -> Cyrl
    2617, 100,  // os -> Cyrl
    2620, 400,  // osa -> Osge
    2624, 200,  // osc -> Ital
    2628, 205,  // osi -> Java
    2632, 10,  // ota -> Arab
    2636, 555,  // otb -> Tibt
    2640, 390,  // otk -> Orkh
    2644, 145,  // oty -> Gran
    2648, 405,  // oui -> Ougr
    2652, 160,  // pa -> Guru
    2655, 10,  // pa_PK -> Arab
    2661, 415,  // pal -> Phli
    2665, 100,  // paq -> Cyrl
    2669, 10,  // pbt -> Arab
    2673, 235,  // pcb -> Khmr
    2677, 355,  // pce -> Mymr
    2681, 330,  // pcf -> Mlym
    2685, 330,  // pcg -> Mlym
    2689, 105,  // pch -> Deva
    2693, 105,  // pci -> Deva
    2697, 535,  // pcj -> Telu
    2701, 395,  // peg -> Orya
    2705, 585,  // peo -> Xpeo
    2709, 230,  // pgd -> Khar
    2713, 105,  // pgg -> Deva
    2717, 380,  // pgl -> Ogam
    2721, 200,  // pgn -> Ital
    2725, 105,  // phd -> Deva
    2729, 355,  // phk -> Mymr
    2733, 10,  // phl -> Arab
    2737, 420,  // phn -> Phnx
    2741, 260,  // pho -> Laoo
    2745, 10,  // phr -> Arab
    2749, 550,  // pht -> Thai
    2753, 550,  // phu -> Thai
    2757, 10,  // phv -> Arab
    2761, 105,  // phw -> Deva
    2765, 470,  // pi -> Sinh
    2768, 55,  // pka -> Brah
    2772, 330,  // pkr -> Mlym
    2776, 10,  // plk -> Arab
    2780, 355,  // pll -> Mymr
    2784, 55,  // pmh -> Brah
    2788, 150,  // pnt -> Grek
    2792, 230,  // pra -> Khar
    2796, 10,  // prc -> Arab
    2800, 10,  // prd -> Arab
    2804, 550,  // prt -> Thai
    2808, 10,  // prx -> Arab
    2812, 10,  // ps -> Arab
    2815, 10,  // psh -> Arab
    2819, 10,  // psi -> Arab
    2823, 10,  // pst -> Arab
    2827, 55,  // psu -> Brah
    2831, 105,  // pum -> Deva
    2835, 355,  // pwo -> Mymr
    2839, 105,  // pwr -> Deva
    2843, 550,  // pww -> Thai
    2847, 355,  // pyx -> Mymr
    2851, 10,  // qxq -> Arab
    2855, 105,  // raa -> Deva
    2859, 105,  // rab -> Deva
    2863, 105,  // raf -> Deva
    2867, 45,  // rah -> Beng
    2871, 105,  // raj -> Deva
    2875, 105,  // rav -> Deva
    2879, 355,  // rbb -> Mymr
    2883, 10,  // rdb -> Arab
    2887, 395,  // rei -> Orya
    2891, 440,  // rhg -> Rohg
    2895, 105,  // rji -> Deva
    2899, 105,  // rjs -> Deva
    2903, 235,  // rka -> Khmr
    2907, 355,  // rki -> Mymr
    2911, 45,  // rkt -> Beng
    2915, 20,  // rmi -> Armn
    2919, 10,  // rmt -> Arab
    2923, 355,  // rmz -> Mymr
    2927, 100,  // rsk -> Cyrl
    2931, 105,  // rtw -> Deva
    2935, 100,  // ru -> Cyrl
    2938, 100,  // rue -> Cyrl
    2942, 100,  // rut -> Cyrl
    2946, 105,  // rwr -> Deva
    2950, 220,  // ryu -> Kana
    2954, 105,  // sa -> Deva
    2957, 100,  // sah -> Cyrl
    2961, 450,  // sam -> Samr
    2965, 385,  // sat -> Olck
    2969, 460,  // saz -> Saur
    2973, 10,  // sbn -> Arab
    2977, 555,  // sbu -> Tibt
    2981, 105,  // sck -> Deva
    2985, 10,  // scl -> Arab
    2989, 105,  // scp -> Deva
    2993, 260,  // sct -> Laoo
    2997, 505,  // scu -> Takr
    3001, 150,  // scx -> Grek
    3005, 10,  // sd -> Arab
    3008, 105,  // sd_IN -> Deva
    3014, 10,  // sdb -> Arab
    3018, 10,  // sdf -> Arab
    3022, 10,  // sdg -> Arab
    3026, 10,  // sdh -> Arab
    3030, 45,  // sdr -> Beng
    3034, 10,  // sds -> Arab
    3038, 100,  // sel -> Cyrl
    3042, 425,  // sfm -> Plrd
    3046, 380,  // sga -> Ogam
    3050, 100,  // sgh -> Cyrl
    3054, 105,  // sgj -> Deva
    3058, 10,  // sgr -> Arab
    3062, 555,  // sgt -> Tibt
    3066, 120,  // sgw -> Ethi
    3070, 10,  // sgy -> Arab
    3074, 10,  // shd -> Arab
    3078, 540,  // shi -> Tfng
    3082, 10,  // shm -> Arab
    3086, 355,  // shn -> Mymr
    3090, 10,  // shu -> Arab
    3094, 10,  // shv -> Arab
    3098, 470,  // si -> Sinh
    3101, 100,  // sia -> Cyrl
    3105, 555,  // sip -> Tibt
    3109, 10,  // siy -> Arab
    3113, 10,  // siz -> Arab
    3117, 100,  // sjd -> Cyrl
    3121, 105,  // sjp -> Deva
    3125, 100,  // sjt -> Cyrl
    3129, 550,  // skb -> Thai
    3133, 105,  // skj -> Deva
    3137, 10,  // skr -> Arab
    3141, 595,  // smh -> Yiii
    3145, 450,  // smp -> Samr
    3149, 235,  // smu -> Khmr
    3153, 10,  // smy -> Arab
    3157, 530,  // soa -> Tavt
    3161, 475,  // sog -> Sogd
    3165, 105,  // soi -> Deva
    3169, 550,  // sou -> Thai
    3173, 555,  // spt -> Tibt
    3177, 395,  // spv -> Orya
    3181, 10,  // sqo -> Arab
    3185, 260,  // sqq -> Laoo
    3189, 10,  // sqt -> Arab
    3193, 100,  // sr -> Cyrl
    3196, 480,  // srb -> Sora
    3200, 10,  // srh -> Arab
    3204, 105,  // srx -> Deva
    3208, 10,  // srz -> Arab
    3212, 10,  // ssh -> Arab
    3216, 260,  // sss -> Laoo
    3220, 10,  // sts -> Arab
    3224, 120,  // stv -> Ethi
    3228, 100,  // sty -> Cyrl
    3232, 490,  // suz -> Sunu
    3236, 125,  // sva -> Geor
    3240, 10,  // swb -> Arab
    3244, 170,  // swi -> Hani
    3248, 105,  // swv -> Deva
    3252, 445,  // sxu -> Runr
    3256, 495,  // syc -> Syrc
    3260, 45,  // syl -> Beng
    3264, 495,  // syn -> Syrc
    3268, 495,  // syr -> Syrc
    3272, 105,  // syw -> Deva
    3276, 520,  // ta -> Taml
    3279, 100,  // tab -> Cyrl
    3283, 105,  // taj -> Deva
    3287, 500,  // tbk -> Tagb
    3291, 555,  // tcn -> Tibt
    3295, 355,  // tco -> Mymr
    3299, 520,  // tcx -> Taml
    3303, 245,  // tcy -> Knda
    3307, 540,  // tda -> Tfng
    3311, 105,  // tdb -> Deva
    3315, 510,  // tdd -> Tale
    3319, 105,  // tdg -> Deva
    3323, 105,  // tdh -> Deva
    3327, 535,  // te -> Telu
    3330, 205,  // tes -> Java
    3334, 100,  // tg -> Cyrl
    3337, 10,  // tg_PK -> Arab
    3343, 105,  // tge -> Deva
    3347, 555,  // tgf -> Tibt
    3351, 550,  // th -> Thai
    3354, 105,  // the -> Deva
    3358, 105,  // thf -> Deva
    3362, 510,  // thi -> Tale
    3366, 105,  // thl -> Deva
    3370, 550,  // thm -> Thai
    3374, 105,  // thq -> Deva
    3378, 105,  // thr -> Deva
    3382, 105,  // ths -> Deva
    3386, 120,  // ti -> Ethi
    3389, 120,  // tig -> Ethi
    3393, 105,  // tij -> Deva
    3397, 100,  // tin -> Cyrl
    3401, 355,  // tjl -> Mymr
    3405, 10,  // tjo -> Arab
    3409, 105,  // tkb -> Deva
    3413, 10,  // tks -> Arab
    3417, 105,  // tkt -> Deva
    3421, 495,  // tmr -> Syrc
    3425, 60,  // tnv -> Cakm
    3429, 10,  // tov -> Arab
    3433, 235,  // tpu -> Khmr
    3437, 10,  // tra -> Arab
    3441, 185,  // trg -> Hebr
    3445, 10,  // trm -> Arab
    3449, 10,  // trw -> Arab
    3453, 150,  // tsd -> Grek
    3457, 555,  // tsj -> Tibt
    3461, 100,  // tt -> Cyrl
    3464, 260,  // tth -> Laoo
    3468, 260,  // tto -> Laoo
    3472, 550,  // tts -> Thai
    3476, 105,  // ttz -> Deva
    3480, 355,  // tvn -> Mymr
    3484, 105,  // twm -> Deva
    3488, 525,  // txg -> Tang
    3492, 565,  // txo -> Toto
    3496, 530,  // tyr -> Tavt
    3500, 100,  // tyv -> Cyrl
    3504, 100,  // ude -> Cyrl
    3508, 330,  // udg -> Mlym
    3512, 100,  // udi -> Cyrl
    3516, 100,  // udm -> Cyrl
    3520, 10,  // ug -> Arab
    3523, 100,  // ug_KZ -> Cyrl
    3529, 100,  // ug_MN -> Cyrl
    3535, 570,  // uga -> Ugar
    3539, 100,  // ugh -> Cyrl
    3543, 550,  // ugo -> Thai
    3547, 100,  // uk -> Cyrl
    3550, 395,  // uki -> Orya
    3554, 100,  // ulc -> Cyrl
    3558, 45,  // unr -> Beng
    3562, 105,  // unr_NP -> Deva
    3569, 45,  // unx -> Beng
    3573, 10,  // ur -> Arab
    3576, 550,  // urk -> Thai
    3580, 10,  // ush -> Arab
    3584, 150,  // uum -> Grek
    3588, 10,  // uz_AF -> Arab
    3594, 100,  // uz_CN -> Cyrl
    3600, 10,  // uzs -> Arab
    3604, 520,  // vaa -> Taml
    3608, 10,  // vaf -> Arab
    3612, 105,  // vah -> Deva
    3616, 575,  // vai -> Vaii
    3620, 105,  // vas -> Deva
    3624, 105,  // vav -> Deva
    3628, 105,  // vay -> Deva
    3632, 10,  // vgr -> Arab
    3636, 105,  // vjk -> Deva
    3640, 245,  // vmd -> Knda
    3644, 10,  // vmh -> Arab
    3648, 120,  // wal -> Ethi
    3652, 10,  // wbk -> Arab
    3656, 535,  // wbq -> Telu
    3660, 105,  // wbr -> Deva
    3664, 120,  // wle -> Ethi
    3668, 10,  // wlo -> Arab
    3672, 105,  // wme -> Deva
    3676, 10,  // wne -> Arab
    3680, 10,  // wni -> Arab
    3684, 130,  // wsg -> Gong
    3688, 10,  // wsv -> Arab
    3692, 105,  // wtm -> Deva
    3696, 175,  // wuu -> Hans
    3700, 0,  // xag -> Aghb
    3704, 100,  // xal -> Cyrl
    3708, 120,  // xan -> Ethi
    3712, 100,  // xas -> Cyrl
    3716, 85,  // xco -> Chrs
    3720, 70,  // xcr -> Cari
    3724, 100,  // xdq -> Cyrl
    3728, 10,  // xhe -> Arab
    3732, 235,  // xhm -> Khmr
    3736, 395,  // xis -> Orya
    3740, 10,  // xka -> Arab
    3744, 10,  // xkc -> Arab
    3748, 555,  // xkf -> Tibt
    3752, 10,  // xkj -> Arab
    3756, 10,  // xkp -> Arab
    3760, 295,  // xlc -> Lyci
    3764, 300,  // xld -> Lydi
    3768, 115,  // xly -> Elym
    3772, 125,  // xmf -> Geor
    3776, 310,  // xmn -> Mani
    3780, 325,  // xmr -> Merc
    3784, 360,  // xna -> Narb
    3788, 105,  // xnr -> Deva
    3792, 150,  // xpg -> Grek
    3796, 380,  // xpi -> Ogam
    3800, 100,  // xpm -> Cyrl
    3804, 430,  // xpr -> Prti
    3808, 100,  // xrm -> Cyrl
    3812, 100,  // xrn -> Cyrl
    3816, 455,  // xsa -> Sarb
    3820, 105,  // xsr -> Deva
    3824, 55,  // xtq -> Brah
    3828, 520,  // xub -> Taml
    3832, 520,  // xuj -> Taml
    3836, 200,  // xve -> Ital
    3840, 10,  // xvi -> Arab
    3844, 100,  // xwo -> Cyrl
    3848, 315,  // xzh -> Marc
    3852, 100,  // yai -> Cyrl
    3856, 105,  // ybh -> Deva
    3860, 105,  // ybi -> Deva
    3864, 10,  // ydg -> Arab
    3868, 330,  // yea -> Mlym
    3872, 150,  // yej -> Grek
    3876, 535,  // yeu -> Telu
    3880, 425,  // ygp -> Plrd
    3884, 185,  // yhd -> Hebr
    3888, 185,  // yi -> Hebr
    3891, 595,  // yig -> Yiii
    3895, 185,  // yih -> Hebr
    3899, 595,  // yiv -> Yiii
    3903, 100,  // ykg -> Cyrl
    3907, 100,  // ykh -> Cyrl
    3911, 425,  // yna -> Plrd
    3915, 100,  // ynk -> Cyrl
    3919, 210,  // yoi -> Jpan
    3923, 550,  // yoy -> Thai
    3927, 100,  // yrk -> Cyrl
    3931, 595,  // ysd -> Yiii
    3935, 595,  // ysn -> Yiii
    3939, 595,  // ysp -> Yiii
    3943, 100,  // ysr -> Cyrl
    3947, 425,  // ysy -> Plrd
    3951, 185,  // yud -> Hebr
    3955, 180,  // yue -> Hant
    3959, 175,  // yue_CN -> Hans
    3966, 100,  // yug -> Cyrl
    3970, 100,  // yux -> Cyrl
    3974, 425,  // ywq -> Plrd
    3978, 425,  // ywu -> Plrd
    3982, 555,  // zau -> Tibt
    3986, 10,  // zba -> Arab
    3990, 170,  // zch -> Hani
    3994, 10,  // zdj -> Arab
    3998, 170,  // zeh -> Hani
    4002, 540,  // zen -> Tfng
    4006, 170,  // zgb -> Hani
    4010, 540,  // zgh -> Tfng
    4014, 170,  // zgm -> Hani
    4018, 170,  // zgn -> Hani
    4022, 175,  // zh -> Hans
    4025, 180,  // zh_AU -> Hant
    4031, 180,  // zh_BN -> Hant
    4037, 180,  // zh_GB -> Hant
    4043, 180,  // zh_GF -> Hant
    4049, 180,  // zh_HK -> Hant
    4055, 180,  // zh_ID -> Hant
    4061, 180,  // zh_MO -> Hant
    4067, 180,  // zh_PA -> Hant
    4073, 180,  // zh_PF -> Hant
    4079, 180,  // zh_PH -> Hant
    4085, 180,  // zh_SR -> Hant
    4091, 180,  // zh_TH -> Hant
    4097, 180,  // zh_TW -> Hant
    4103, 180,  // zh_US -> Hant
    4109, 180,  // zh_VN -> Hant
    4115, 170,  // zhd -> Hani
    4119, 375,  // zhx -> Nshu
    4123, 100,  // zko -> Cyrl
    4127, 240,  // zkt -> Kits
    4131, 100,  // zkz -> Cyrl
    4135, 170,  // zlj -> Hani
    4139, 170,  // zln -> Hani
    4143, 170,  // zlq -> Hani
    4147, 170,  // zqe -> Hani
    4151, 395,  // zrg -> Orya
    4155, 185,  // zrp -> Hebr
    4159, 10,  // zum -> Arab
    4163, 120,  // zwa -> Ethi
    4167, 170,  // zyg -> Hani
    4171, 170,  // zyn -> Hani
    4175, 170,  // zzj -> Hani
};

//======================================================================
// Parent locale table
const char parentLocaleChars[] =
    "az_Arab\0az_Cyrl\0bal_Latn\0blt_Latn\0bm_Nkoo\0bs_Cyrl\0byn_Latn\0"
    "cu_Glag\0dje_Arab\0dyo_Arab\0en_001\0en_150\0en_AG\0en_AI\0en_AT\0"
    "en_AU\0en_BB\0en_BE\0en_BM\0en_BS\0en_BW\0en_BZ\0en_CC\0en_CH\0"
    "en_CK\0en_CM\0en_CX\0en_CY\0en_CZ\0en_DE\0en_DG\0en_DK\0en_DM\0"
    "en_Dsrt\0en_ER\0en_ES\0en_FI\0en_FJ\0en_FK\0en_FM\0en_FR\0en_GB\0"
    "en_GD\0en_GG\0en_GH\0en_GI\0en_GM\0en_GY\0en_HK\0en_HU\0en_ID\0"
    "en_IE\0en_IL\0en_IM\0en_IN\0en_IO\0en_IT\0en_JE\0en_JM\0en_KE\0"
    "en_KI\0en_KN\0en_KY\0en_LC\0en_LR\0en_LS\0en_MG\0en_MO\0en_MS\0"
    "en_MT\0en_MU\0en_MV\0en_MW\0en_MY\0en_NA\0en_NF\0en_NG\0en_NL\0"
    "en_NO\0en_NR\0en_NU\0en_NZ\0en_PG\0en_PK\0en_PL\0en_PN\0en_PT\0"
    "en_PW\0en_RO\0en_RW\0en_SB\0en_SC\0en_SD\0en_SE\0en_SG\0en_SH\0"
    "en_SI\0en_SK\0en_SL\0en_SS\0en_SX\0en_SZ\0en_Shaw\0en_TC\0en_TK\0"
    "en_TO\0en_TT\0en_TV\0en_TZ\0en_UG\0en_VC\0en_VG\0en_VU\0en_WS\0"
    "en_ZA\0en_ZM\0en_ZW\0es_419\0es_AR\0es_BO\0es_BR\0es_BZ\0es_CL\0"
    "es_CO\0es_CR\0es_CU\0es_DO\0es_EC\0es_GT\0es_HN\0es_JP\0es_MX\0"
    "es_NI\0es_PA\0es_PE\0es_PR\0es_PY\0es_SV\0es_US\0es_UY\0es_VE\0"
    "ff_Adlm\0ff_Arab\0fr_HT\0ha_Arab\0hi_Latn\0ht\0iu_Latn\0kaa_Latn\0"
    "kk_Arab\0kok_Latn\0ks_Deva\0ku_Arab\0kxv_Deva\0kxv_Orya\0kxv_Telu\0"
    "ky_Arab\0ky_Latn\0ml_Arab\0mn_Mong\0mni_Mtei\0ms_Arab\0nb\0nn\0"
    "no\0no_NO\0pa_Arab\0pt_AO\0pt_CH\0pt_CV\0pt_FR\0pt_GQ\0pt_GW\0"
    "pt_LU\0pt_MO\0pt_MZ\0pt_PT\0pt_ST\0pt_TL\0root\0sat_Deva\0sd_Deva\0"
    "sd_Khoj\0sd_Sind\0shi_Latn\0so_Arab\0sr_Latn\0sw_Arab\0tg_Arab\0"
    "ug_Cyrl\0uz_Arab\0uz_Cyrl\0vai_Latn\0wo_Arab\0yo_Arab\0yue_Hans\0"
    "zh_Hant\0zh_Hant_HK\0zh_Hant_MO\0";

const int32_t parentLocaleTable[] = {
    0, 1140,  // az_Arab -> root
    8, 1140,  // az_Cyrl -> root
    16, 1140,  // bal_Latn -> root
    25, 1140,  // blt_Latn -> root
    34, 1140,  // bm_Nkoo -> root
    42, 1140,  // bs_Cyrl -> root
    50, 1140,  // byn_Latn -> root
    59, 1140,  // cu_Glag -> root
    67, 1140,  // dje_Arab -> root
    76, 1140,  // dyo_Arab -> root
    92, 85,  // en_150 -> en_001
    99, 85,  // en_AG -> en_001
    105, 85,  // en_AI -> en_001
    111, 92,  // en_AT -> en_150
    117, 85,  // en_AU -> en_001
    123, 85,  // en_BB -> en_001
    129, 92,  // en_BE -> en_150
    135, 85,  // en_BM -> en_001
    141, 85,  // en_BS -> en_001
    147, 85,  // en_BW -> en_001
    153, 85,  // en_BZ -> en_001
    159, 85,  // en_CC -> en_001
    165, 92,  // en_CH -> en_150
    171, 85,  // en_CK -> en_001
    177, 85,  // en_CM -> en_001
    183, 85,  // en_CX -> en_001
    189, 85,  // en_CY -> en_001
    195, 92,  // en_CZ -> en_150
    201, 92,  // en_DE -> en_150
    207, 85,  // en_DG -> en_001
    213, 92,  // en_DK -> en_150
    219, 85,  // en_DM -> en_001
    225, 1140,  // en_Dsrt -> root
    233, 85,  // en_ER -> en_001
    239, 92,  // en_ES -> en_150
    245, 92,  // en_FI -> en_150
    251, 85,  // en_FJ -> en_001
    257, 85,  // en_FK -> en_001
    263, 85,  // en_FM -> en_001
    269, 92,  // en_FR -> en_150
    275, 85,  // en_GB -> en_001
    281, 85,  // en_GD -> en_001
    287, 85,  // en_GG -> en_001
    293, 85,  // en_GH -> en_001
    299, 85,  // en_GI -> en_001
    305, 85,  // en_GM -> en_001
    311, 85,  // en_GY -> en_001
    317, 85,  // en_HK -> en_001
    323, 92,  // en_HU -> en_150
    329, 85,  // en_ID -> en_001
    335, 85,  // en_IE -> en_001
    341, 85,  // en_IL -> en_001
    347, 85,  // en_IM -> en_001
    353, 85,  // en_IN -> en_001
    359, 85,  // en_IO -> en_001
    365, 92,  // en_IT -> en_150
    371, 85,  // en_JE -> en_001
    377, 85,  // en_JM -> en_001
    383, 85,  // en_KE -> en_001
    389, 85,  // en_KI -> en_001
    395, 85,  // en_KN -> en_001
    401, 85,  // en_KY -> en_001
    407, 85,  // en_LC -> en_001
    413, 85,  // en_LR -> en_001
    419, 85,  // en_LS -> en_001
    425, 85,  // en_MG -> en_001
    431, 85,  // en_MO -> en_001
    437, 85,  // en_MS -> en_001
    443, 85,  // en_MT -> en_001
    449, 85,  // en_MU -> en_001
    455, 85,  // en_MV -> en_001
    461, 85,  // en_MW -> en_001
    467, 85,  // en_MY -> en_001
    473, 85,  // en_NA -> en_001
    479, 85,  // en_NF -> en_001
    485, 85,  // en_NG -> en_001
    491, 92,  // en_NL -> en_150
    497, 92,  // en_NO -> en_150
    503, 85,  // en_NR -> en_001
    509, 85,  // en_NU -> en_001
    515, 85,  // en_NZ -> en_001
    521, 85,  // en_PG -> en_001
    527, 85,  // en_PK -> en_001
    533, 92,  // en_PL -> en_150
    539, 85,  // en_PN -> en_001
    545, 92,  // en_PT -> en_150
    551, 85,  // en_PW -> en_001
    557, 92,  // en_RO -> en_150
    563, 85,  // en_RW -> en_001
    569, 85,  // en_SB -> en_001
    575, 85,  // en_SC -> en_001
    581, 85,  // en_SD -> en_001
    587, 92,  // en_SE -> en_150
    593, 85,  // en_SG -> en_001
    599, 85,  // en_SH -> en_001
    605, 92,  // en_SI -> en_150
    611, 92,  // en_SK -> en_150
    617, 85,  // en_SL -> en_001
    623, 85,  // en_SS -> en_001
    629, 85,  // en_SX -> en_001
    635, 85,  // en_SZ -> en_001
    641, 1140,  // en_Shaw -> root
    649, 85,  // en_TC -> en_001
    655, 85,  // en_TK -> en_001
    661, 85,  // en_TO -> en_001
    667, 85,  // en_TT -> en_001
    673, 85,  // en_TV -> en_001
    679, 85,  // en_TZ -> en_001
    685, 85,  // en_UG -> en_001
    691, 85,  // en_VC -> en_001
    697, 85,  // en_VG -> en_001
    703, 85,  // en_VU -> en_001
    709, 85,  // en_WS -> en_001
    715, 85,  // en_ZA -> en_001
    721, 85,  // en_ZM -> en_001
    727, 85,  // en_ZW -> en_001
    740, 733,  // es_AR -> es_419
    746, 733,  // es_BO -> es_419
    752, 733,  // es_BR -> es_419
    758, 733,  // es_BZ -> es_419
    764, 733,  // es_CL -> es_419
    770, 733,  // es_CO -> es_419
    776, 733,  // es_CR -> es_419
    782, 733,  // es_CU -> es_419
    788, 733,  // es_DO -> es_419
    794, 733,  // es_EC -> es_419
    800, 733,  // es_GT -> es_419
    806, 733,  // es_HN -> es_419
    812, 733,  // es_JP -> es_419
    818, 733,  // es_MX -> es_419
    824, 733,  // es_NI -> es_419
    830, 733,  // es_PA -> es_419
    836, 733,  // es_PE -> es_419
    842, 733,  // es_PR -> es_419
    848, 733,  // es_PY -> es_419
    854, 733,  // es_SV -> es_419
    860, 733,  // es_US -> es_419
    866, 733,  // es_UY -> es_419
    872, 733,  // es_VE -> es_419
    878, 1140,  // ff_Adlm -> root
    886, 1140,  // ff_Arab -> root
    900, 1140,  // ha_Arab -> root
    908, 353,  // hi_Latn -> en_IN
    916, 894,  // ht -> fr_HT
    919, 1140,  // iu_Latn -> root
    927, 1140,  // kaa_Latn -> root
    936, 1140,  // kk_Arab -> root
    944, 1140,  // kok_Latn -> root
    953, 1140,  // ks_Deva -> root
    961, 1140,  // ku_Arab -> root
    969, 1140,  // kxv_Deva -> root
    978, 1140,  // kxv_Orya -> root
    987, 1140,  // kxv_Telu -> root
    996, 1140,  // ky_Arab -> root
    1004, 1140,  // ky_Latn -> root
    1012, 1140,  // ml_Arab -> root
    1020, 1140,  // mn_Mong -> root
    1028, 1140,  // mni_Mtei -> root
    1037, 1140,  // ms_Arab -> root
    1045, 1051,  // nb -> no
    1048, 1051,  // nn -> no
    1054, 1051,  // no_NO -> no
    1060, 1140,  // pa_Arab -> root
    1068, 1122,  // pt_AO -> pt_PT
    1074, 1122,  // pt_CH -> pt_PT
    1080, 1122,  // pt_CV -> pt_PT
    1086, 1122,  // pt_FR -> pt_PT
    1092, 1122,  // pt_GQ -> pt_PT
    1098, 1122,  // pt_GW -> pt_PT
    1104, 1122,  // pt_LU -> pt_PT
    1110, 1122,  // pt_MO -> pt_PT
    1116, 1122,  // pt_MZ -> pt_PT
    1128, 1122,  // pt_ST -> pt_PT
    1134, 1122,  // pt_TL -> pt_PT
    1145, 1140,  // sat_Deva -> root
    1154, 1140,  // sd_Deva -> root
    1162, 1140,  // sd_Khoj -> root
    1170, 1140,  // sd_Sind -> root
    1178, 1140,  // shi_Latn -> root
    1187, 1140,  // so_Arab -> root
    1195, 1140,  // sr_Latn -> root
    1203, 1140,  // sw_Arab -> root
    1211, 1140,  // tg_Arab -> root
    1219, 1140,  // ug_Cyrl -> root
    1227, 1140,  // uz_Arab -> root
    1235, 1140,  // uz_Cyrl -> root
    1243, 1140,  // vai_Latn -> root
    1252, 1140,  // wo_Arab -> root
    1260, 1140,  // yo_Arab -> root
    1268, 1140,  // yue_Hans -> root
    1277, 1140,  // zh_Hant -> root
    1296, 1285,  // zh_Hant_MO -> zh_Hant_HK
};


#endif  // INCLUDED_FROM_URESBUND_CPP
